### ISSUE TITLE
How can I upload a file into the CLM folder of my record using Apex?

### ISSUE THREAD

**Issue by franciscoFlock** [docusign/code-examples-clm-apex#3]
Sorry, I know this is not an issue but couldn't find any documentation to help me with this... maybe I'm not using the correct keywords for my search...
I was hoping to find here on the code-examples-clm-apex a way to upload a file (pdf) to the CLM folder using Apex but here I only see on the SRC folder how to connect and get the folder to view it? How can I do the upload?
Please help me on guiding me to the correct documentation.

**Comment by RobWiley-ds** [comment]
You will need to use the Upload method of the Content API. The documentation for the Content API, and other CLM APIs can be found here: https://developers.docusign.com/docs/clm-api/clm101/content-api/ . Swagger documentation can be found here: https://apidocsna11.springcm.com/apidocs/webapiv2

**Comment by franciscoFlock** [comment]
Thanks! you saved me @RobWiley-ds
